name: Build LangTray

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  msvc:
    name: MSVC ${{ matrix.arch }}
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x64, x86]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSVC dev cmd
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}

      - name: Build (MSVC ${{ matrix.arch }})
        shell: pwsh
        run: |
          # Собираем GUI-приложение, источник — UTF-8
          cl /nologo /O2 /utf-8 LangTray.cpp /DUNICODE /D_UNICODE /link /SUBSYSTEM:WINDOWS user32.lib shell32.lib gdi32.lib advapi32.lib

          New-Item -ItemType Directory -Force -Path dist | Out-Null
          Move-Item LangTray.exe "dist/LangTray-msvc-${{ matrix.arch }}.exe"

      - name: Package ZIP (MSVC ${{ matrix.arch }})
        shell: pwsh
        run: |
          $pkgName = "LangTray-msvc-${{ matrix.arch }}"
          $pkgDir  = "package/$pkgName"
          New-Item -ItemType Directory -Force -Path $pkgDir | Out-Null

          # В ZIP кладём файл с именем LangTray.exe
          Copy-Item "dist/$pkgName.exe" "$pkgDir/LangTray.exe"

          if (Test-Path "icons") {
            Copy-Item -Recurse -Force "icons" "$pkgDir/icons"
          } else {
            Write-Host "icons/ не найдена — в ZIP попадёт только LangTray.exe"
          }

          New-Item -ItemType Directory -Force -Path dist | Out-Null
          Compress-Archive -Force -CompressionLevel Optimal -Path "$pkgDir/*" -DestinationPath "dist/$pkgName.zip"

      - name: Upload ZIP artifact (MSVC ${{ matrix.arch }})
        uses: actions/upload-artifact@v4
        with:
          name: LangTray-msvc-${{ matrix.arch }}-zip
          path: dist/LangTray-msvc-${{ matrix.arch }}.zip

  mingw:
    name: MinGW ${{ matrix.msystem }}
    runs-on: windows-latest
    strategy:
      matrix:
        msystem: [MINGW64, MINGW32]
        include:
          - msystem: MINGW64
            pkg: mingw-w64-x86_64-toolchain
            exe: LangTray-mingw64.exe
            zip: LangTray-mingw64.zip
          - msystem: MINGW32
            pkg: mingw-w64-i686-toolchain
            exe: LangTray-mingw32.exe
            zip: LangTray-mingw32.zip

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2 (${{ matrix.msystem }})
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: ${{ matrix.pkg }}
          update: true

      - name: Build (${{ matrix.msystem }})
        shell: msys2 {0}
        run: |
          # GUI-подсистема (-mwindows), источник в UTF-8, Unicode-entrpoint
          g++ -O2 -municode -mwindows -finput-charset=UTF-8 LangTray.cpp -o ${{ matrix.exe }} -luser32 -lshell32 -lgdi32 -ladvapi32
          mkdir -p dist
          mv ${{ matrix.exe }} dist/

      - name: Package ZIP (${{ matrix.msystem }})
        shell: pwsh
        run: |
          $pkgName = "${{ matrix.zip }}".Replace(".zip","")
          $pkgDir  = "package/$pkgName"
          New-Item -ItemType Directory -Force -Path $pkgDir | Out-Null

          # В ZIP кладём файл с именем LangTray.exe
          Copy-Item "dist/${{ matrix.exe }}" "$pkgDir/LangTray.exe"

          if (Test-Path "icons") {
            Copy-Item -Recurse -Force "icons" "$pkgDir/icons"
          } else {
            Write-Host "icons/ не найдена — в ZIP попадёт только LangTray.exe"
          }

          New-Item -ItemType Directory -Force -Path dist | Out-Null
          Compress-Archive -Force -CompressionLevel Optimal -Path "$pkgDir/*" -DestinationPath "dist/${{ matrix.zip }}"

      - name: Upload ZIP artifact (${{ matrix.msystem }})
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.zip }}
          path: dist/${{ matrix.zip }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [msvc, mingw]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
          pattern: '*'
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
